### ISSUE TITLE
Add Security Observability support

### ISSUE THREAD

**Issue by nwmac** [SUSE/stratos#401]
- ~~Reports are shown for ALL endpoints, not just the chosen endpoint - NM~~
- ~~Errors parsing kubecf release in the Workload summary - NM~~
~~- Errors not available for when a report failed - e.g. "could not contact analysis server"~~
~~- Can still click on report name when there is an error - get failed to load report~~
- ~~Failed to delete report when failed to contact analysis server~~
~~- Can view report even when job is still running~~
- PopEye report view needs improvement - e.g. add icons for resource type and improve layout. Allow expand/collapse of resources
- ~~Workload Analysis tab is empty if no analysis has been run - should show a message and allow one to be run OR should be hidden until an analysis is available~~
- ~~Restructure for new extensions folder~~
- ~~Update CI to build the analysers image as well - NM~~
- ~~Rebase PR with master~~
- Tidy up PR
- ~~JUNIT Report is work in progress~~ - removed
- ~~Only enable popeye (allow kubescore as well via config?) - Remove Sonobuoy from the image - NM~~
- Remove any console.log messages
- Filter workload analysis to only include resources in the workload
- ~~Move helm chart customizations to the custom-src folder~~
- ~~Delete all analysis reports when an endpoint is unregistered - NM~~
- ~~Report name does not update to a link when report is available~~
- Add support for viewing log of a run
- ~~Change Analyzer Info to a slide-in (since it is now available in different places and the nav context changes). Remove icons, since I'm not sure the PopEye icon is legit~~

**Comment by richard-cox** [comment]
Here's some things i picked up on 

General
- ~~On the info and report pages the user has to click on the analysis link again to get back. feels like this needs an `x`. I don't think we have a pattern for sub-pages in secondary tab sections NM~~

Analysis Page
- ~~When a new analysis is run the list refreshes and the sort order gets lost... probably a facet of the reset pagination process~~
- ~~This shows the same list content for all connected kubes, needs a filter on endpoint guid~~

Table
- ~~should the default sort order be on age?~~
- ~~row action menu 'delete' section - icon and label odd, icon width should be smaller. could be a problem with the underlying action menu~~

Report Pages
- ~~These could be titled or topped with the report type and time~~
- Popeye.. on my kind cluster (kind has an ip of 127.0.0.1)
  - the 'group name' section is empty and consumes a large amount of width (i get a score of `27 f` and there are a lot of 
    'connection refused' errors per section. is this to be expected on kind?)
  - the ok/info/warning/error counts could be colour coded  
- Kube score.. on my kind cluster (kind has an ip of 127.0.0.1)
  - i get a status of completed and an empty report page

Namespace Analysis Page
- ~~had to manually refresh browser in order to see first analysis (arrive at page with no analysis associated with namespace, run analysis... nothing shown after refresh button) RC~~
- kube score - shows empty page when run in namespace with no pods (ns contained stratos at one point, which was `helm deleted`)
